### PR TITLE
fix wording

### PR DESCRIPTION
**Pull request by bcuz**

### CODE REVIEW

**Review by arye-eidelman — APPROVED** [review]
looks good

**Comment by bcuz** [comment]
@arye-dov-eidelman is earning karma by submitting a curriculum edit still a thing?

**Comment by arye-eidelman** [comment]
I never heard of that

**Comment by arye-eidelman** [comment]
Dont know [help.learn.co/.../what-is-karma](http://help.learn.co/your-learn-community/karma/what-is-karma) the lesson editer link is broken

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing a pull request, @bcuz.

The change looks good, so we have merged in the changes.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙

**Pull request merged**
